### ISSUE TITLE
thread

### ISSUE THREAD

**Issue by waseem-GitHub-Live** [meetAhmed/Android-VPN-Study#1]
FATAL EXCEPTION: TcpSendWorker
                                                                                                    Process: com.moduscreate.vpn.study, PID: 23238
                                                                                                    java.lang.InterruptedException
                                                                                                    	at java.lang.Thread.sleep(Native Method)
                                                                                                    	at java.lang.Thread.sleep(Thread.java:373)
                                                                                                    	at java.lang.Thread.sleep(Thread.java:314)
                                                                                                    	at com.moduscreate.vpn.study.vpn.tcp.TcpWorker.run(TcpWorker.kt:56)

**Comment by waseem-GitHub-Live** [comment]
FATAL EXCEPTION: Thread-2
                                                                                                    Process: com.moduscreate.vpn.study, PID: 23464
                                                                                                    java.lang.InterruptedException
                                                                                                    	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2034)
                                                                                                    	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2068)
                                                                                                    	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:387)
                                                                                                    	at com.moduscreate.vpn.study.vpn.udp.UdpSendWorker.run(UdpSendWorker.kt:48)
                                                                                                    	
 after stop

**Comment by meetAhmed** [comment]
Hi @waseem-GitHub-Live. Are you still facing this issue? Any steps to reproduce this.

**Comment by waseem-GitHub-Live** [comment]
hi @meetAhmed i dont remember now, i alredy did that type of project with other methods thanks tho
